export const MessageCodes = {
  AUTH_EMAIL_ALREADY_REGISTERED_VERIFIED:
    'AUTH_EMAIL_ALREADY_REGISTERED_VERIFIED',
  AUTH_EMAIL_ALREADY_REGISTERED_UNVERIFIED:
    'AUTH_EMAIL_ALREADY_REGISTERED_UNVERIFIED',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
  AUTH_UNEXPECTED_REGISTRATION_STATE: 'AUTH_UNEXPECTED_REGISTRATION_STATE',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_REGISTER_SUCCESS: 'AUTH_REGISTER_SUCCESS',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',

  OTP_REQUIRED: 'OTP_REQUIRED',
  OTP_EXPIRED_OR_INVALID: 'OTP_EXPIRED_OR_INVALID',
  OTP_INCORRECT: 'OTP_INCORRECT',
  OTP_VERIFIED_SUCCESS: 'OTP_VERIFIED_SUCCESS',
  OTP_RESEND_COOLDOWN_ACTIVE: 'OTP_RESEND_COOLDOWN_ACTIVE',
  OTP_RESENT_SUCCESS: 'OTP_RESENT_SUCCESS',

  VALIDATION_EMAIL_REQUIRED: 'VALIDATION_EMAIL_REQUIRED',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  VALIDATION_EMAIL_PASSWORD_REQUIRED: 'VALIDATION_EMAIL_PASSWORD_REQUIRED',
  VALIDATION_EMAIL_PASSWORD_INVALID: 'VALIDATION_EMAIL_PASSWORD_INVALID',
  VALIDATION_EMAIL_OTP_REQUIRED: 'VALIDATION_EMAIL_OTP_REQUIRED',
  VALIDATION_EMAIL_OTP_INVALID: 'VALIDATION_EMAIL_OTP_INVALID',

  EMAIL_SERVICE_NOT_CONFIGURED: 'EMAIL_SERVICE_NOT_CONFIGURED',
  EMAIL_UNKNOWN_ERROR: 'EMAIL_UNKNOWN_ERROR',

  SYSTEM_INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SYSTEM_DATABASE_CONNECTION_FAILED: 'SYSTEM_DATABASE_CONNECTION_FAILED',
  SYSTEM_DATABASE_CONNECTED: 'SYSTEM_DATABASE_CONNECTED',

  REDIS_OTP_STORAGE_FAILED: 'REDIS_OTP_STORAGE_FAILED',
} as const;

export type TMessageCode = (typeof MessageCodes)[keyof typeof MessageCodes];
